coverage:
  status:
    project:
      default:
        # Don't allow code coverage to be reduced.
        target: auto
        threshold: 0%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false # if true: only post the comment if coverage changes
  require_base: "no" # [yes :: must have a base report to post]
  require_head: "yes" # [yes :: must have a head report to post]
