# Copyright 2026 Ian Lewis
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: must be named `autofix.ci` to securely identify the workflow
name: autofix.ci

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

permissions: {}

concurrency:
  group: autofix-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

jobs:
  autofix:
    name: autofix
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: true
          persist-credentials: false

      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version-file: ".node-version"

      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version-file: ".python-version"

      - name: update lockfiles
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make update-lockfiles

      - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a # v1.3.4
        with:
          commit-message: "ci(deps): update lockfiles"
